@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.player005.vegandelightfabric;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
