name: build-release

on:
  release:
    types:
      - published
      - edited

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: 'temurin'
          java-version: 21
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build

      - name: Upload artifacts to Modrinth and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: vtNhfMsL
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          curseforge-id: 1112658
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs/!(*-@(dev|sources|all)).jar
          
          version-type: release
          loaders: fabric quilt
          version-resolver: latest

          dependencies: |
            fabric-api
            farmers-delight-refabricated
            farmers-delight-fabric(incompatible)
